# Copyright (c) 2025 Eclipse Foundation.
# 
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT

services:
  playground-fe:
    container_name: ${ENV:-dev}-playground-fe
    image: boschvn/playground-fe:${IMAGE_TAG:-latest}
    ports:
      - "${APP_PORT:-8090}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
