# Copyright (c) 2025 Eclipse Foundation.
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT

# AutoWRX v3 Stack
# Usage:
#   docker compose -f docker-compose.stack.yml --env-file .env.stack up -d

services:
  # AutoWRX - Backend serves both API and frontend static files
  autowrx:
    platform: linux/amd64
    container_name: ${ENV:-prod}-autowrx
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY:-eclipse-autowrx/autowrx}/autowrx:${IMAGE_TAG:-latest}
    ports:
      - "${FRONTEND_PORT:-8090}:8080"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 8080
      MONGODB_URL: ${MONGODB_URL:-mongodb://autowrx-db:27017/autowrx-be}
      CORS_ORIGINS: ${CORS_ORIGINS}
      UPLOAD_PORT: ${UPLOAD_PORT:-9810}
      UPLOAD_PATH: ${UPLOAD_PATH:-/opt/data/upload}
      UPLOAD_DOMAIN: ${UPLOAD_DOMAIN:-/api/v2/file/}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION_MINUTES: ${JWT_ACCESS_EXPIRATION_MINUTES:-30}
      JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS:-30}
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${JWT_RESET_PASSWORD_EXPIRATION_MINUTES:-10}
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${JWT_VERIFY_EMAIL_EXPIRATION_MINUTES:-10}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME:-token}
      JWT_COOKIE_DOMAIN: ${JWT_COOKIE_DOMAIN}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL:-http://localhost:8090}
      EMAIL_API_KEY: ${EMAIL_API_KEY}
      EMAIL_ENDPOINT_URL: ${EMAIL_ENDPOINT_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LOGS_MAX_SIZE: ${LOGS_MAX_SIZE:-100}
    volumes:
      - '${UPLOAD_PATH_HOST:-./data/upload}:/opt/data/upload'
    depends_on:
      - autowrx-db
    networks:
      - autowrx-network
    restart: always

  # MongoDB - Database
  autowrx-db:
    platform: linux/amd64
    container_name: ${ENV:-prod}-autowrx-db
    image: mongo:4.4.6-bionic
    volumes:
      - autowrx-dbdata:/data/db
    networks:
      - autowrx-network
    restart: always

volumes:
  autowrx-dbdata:
    name: ${ENV:-prod}-autowrx-dbdata

networks:
  autowrx-network:
    name: ${ENV:-prod}-autowrx-network
    driver: bridge
