# Copyright (c) 2025 Eclipse Foundation.
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT

services:
  kong:
    platform: linux/amd64
    image: boschvn/playground-kong:latest
    container_name: ${ENV:-dev}-kong
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_NGINX_WORKER_PROCESSES: ${KONG_NGINX_WORKER_PROCESSES:-auto}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - '${KONG_PROXY_PORT}:8000'

    restart: always
    networks:
      - node-network
    depends_on:
      - playground-be
      - inventory-be

  playground-be:
    platform: linux/amd64
    container_name: ${ENV:-dev}-playground-be
    build: .
    image: boschvn/playground-be:${IMAGE_TAG:-latest}
    env_file:
      - .env
    depends_on:
      - playground-db
      - upload
    networks:
      - node-network
    restart: always
    command: yarn start

  playground-db:
    container_name: ${DB_CONTAINER_NAME:-playground-db}
    image: mongo:4.4.6-bionic
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
    restart: always

  upload:
    platform: linux/amd64
    container_name: ${ENV:-dev}-upload
    image: boschvn/upload:1.1.0
    env_file:
      - .env
    volumes:
      - '${UPLOAD_PATH}:/usr/src/upload/data'
    networks:
      - node-network
    restart: always
    command: npm run prod

  homologation:
    platform: linux/amd64
    container_name: ${ENV:-dev}-homologation-node
    image: boschvn/homologation-node:latest
    networks:
      - node-network
    environment:
      - HOMOLOGATION_AUTH_CLIENT_ID=${HOMOLOGATION_AUTH_CLIENT_ID}
      - HOMOLOGATION_AUTH_CLIENT_SECRET=${HOMOLOGATION_AUTH_CLIENT_SECRET}

  inventory-be:
    platform: linux/amd64
    container_name: ${ENV:-dev}-inventory-be
    image: boschvn/inventory-be:latest
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URL=mongodb://inventory-db:27017/inventory
      - AUTHORIZATION_URL=http://playground-be:8080/v2/auth/authorize
      - CORS_ORIGIN=${CORS_ORIGINS}
    networks:
      - node-network
    restart: ${RESTART_POLICY:-always}
    command: yarn start
    depends_on:
      - inventory-db

  inventory-db:
    platform: linux/amd64
    container_name: ${ENV:-dev}-inventory-db
    image: mongo:4.4.6-bionic
    volumes:
      - inventorydata:/data/db
    restart: ${RESTART_POLICY:-always}
    networks:
      - node-network

volumes:
  dbdata:
  inventorydata:

networks:
  node-network:
    driver: bridge
