# Copyright (c) 2025 Eclipse Foundation.
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT

services:
  playground-be:
    build:
      context: .
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-eclipse-autowrx}/playground-be:${TAG:-latest}
    command: yarn dev -L
    volumes:
      - .:/usr/src/playground-be
    restart: no
    env_file:
      - .env

  upload:
    command: npm start
    restart: no
    env_file:
      - .env

  playground-db:
    ports:
      - '27017:27017'
    restart: no

  kong:
    restart: no

  genai:
    platform: linux/amd64
    container_name: ${ENV:-dev}-genai
    image: boschvn/genai:latest
    networks:
      - node-network
    env_file:
      - .env
    restart: no

  cache:
    platform: linux/amd64
    container_name: ${ENV:-dev}-cache
    image: boschvn/cache:latest
    networks:
      - node-network
    restart: no

  homologation:
    platform: linux/amd64
    container_name: ${ENV:-dev}-homologation-node
    image: boschvn/homologation-node:latest
    networks:
      - node-network
    restart: no
    environment:
      - HOMOLOGATION_AUTH_CLIENT_ID=${HOMOLOGATION_AUTH_CLIENT_ID}
      - HOMOLOGATION_AUTH_CLIENT_SECRET=${HOMOLOGATION_AUTH_CLIENT_SECRET}

  inventory-be:
    command: yarn dev -L
    restart: no
