// Copyright (c) 2025 Eclipse Foundation.
//
// This program and the accompanying materials are made available under the
// terms of the MIT License which is available at
// https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: MIT

/**
 * Predefined site configs seeded on server startup.
 * These are the source of truth for default values.
 * Values are only inserted if the key does NOT already exist in DB (setOnInsert).
 * Admin-customized values are never overwritten.
 */
const PREDEFINED_SITE_CONFIGS = [
  {
    key: 'SITE_LOGO_WIDE',
    scope: 'site',
    value: '/imgs/logo-wide.png',
    secret: false,
    valueType: 'image_url',
    description: 'Wide logo image displayed in the navigation bar.',
  },
  {
    key: 'DEFAULT_MODEL_IMAGE',
    scope: 'site',
    value: '/imgs/default-model-image.png',
    secret: false,
    valueType: 'image_url',
    description: 'Default image used when creating a new model.',
    category: 'model_prototype',
  },
  {
    key: 'DEFAULT_PROTOTYPE_IMAGE',
    scope: 'site',
    value: '/imgs/default_prototype_cover.jpg',
    secret: false,
    valueType: 'image_url',
    description: 'Default cover image used when creating a new prototype.',
    category: 'model_prototype',
  },
  {
    key: 'SITE_TITLE',
    scope: 'site',
    value: 'Playground | digital.auto',
    secret: false,
    valueType: 'string',
    description: 'Browser tab title and site name.',
  },
  {
    key: 'SITE_DESCRIPTION',
    scope: 'site',
    value: 'Fast prototyping platform for vehicle QM applications',
    secret: false,
    valueType: 'string',
    description: 'Short description of the site.',
  },
  {
    key: 'PRIVACY_POLICY_URL',
    scope: 'site',
    value: '/privacy-policy',
    secret: false,
    valueType: 'string',
    description: 'URL for the Privacy Policy page.',
  },
  {
    key: 'PRIVACY_POLICY_CONTENT',
    scope: 'site',
    value: '',
    secret: false,
    valueType: 'string',
    description: 'Markdown content for the Privacy Policy page displayed at /privacy-policy.',
    category: 'privacy',
  },
  {
    key: 'TERMS_OF_SERVICE_URL',
    scope: 'site',
    value: '/terms-of-service',
    secret: false,
    valueType: 'string',
    description: 'URL for the Terms of Service page.',
  },
  {
    key: 'RUNTIME_SERVER_URL',
    scope: 'site',
    value: 'https://kit.digitalauto.tech',
    secret: false,
    valueType: 'string',
    description: 'Runtime server URL for prototype execution.',
  },
  {
    key: 'RUNTIME_SERVER_CONFIG',
    scope: 'site',
    value: '{}',
    secret: false,
    valueType: 'string',
    description: 'Custom JSON options passed to the Socket.IO client when connecting to the runtime server.',
  },
  {
    key: 'SHOW_CODE_API_PANEL',
    scope: 'site',
    value: true,
    secret: false,
    valueType: 'boolean',
    description: 'Show or hide the API panel on the Prototype Code tab.',
    category: 'model_prototype',
  },
  {
    key: 'SHOW_CODE_DIFF',
    scope: 'site',
    value: false,
    secret: false,
    valueType: 'boolean',
    description: 'Enable the code diff feature on the Prototype Code tab.',
    category: 'genai',
  },
  {
    key: 'DEFAULT_MARKETPLACE_URL',
    scope: 'site',
    value: 'https://marketplace.digitalauto.tech',
    secret: false,
    valueType: 'string',
    description: 'Default marketplace URL for plugins and add-ons.',
  },
  {
    key: 'SUPPORT_CENTER_URL',
    scope: 'site',
    value: 'https://github.com/eclipse-autowrx/autowrx/issues',
    secret: false,
    valueType: 'string',
    description: 'Link to the support center or issue tracker.',
  },
  {
    key: 'ENABLE_LEARNING_MODE',
    scope: 'site',
    value: false,
    secret: false,
    valueType: 'boolean',
    description: 'Enable or disable learning mode.',
  },
  {
    key: 'LEARNING_MODE_URL',
    scope: 'site',
    value: 'https://digital.auto',
    secret: false,
    valueType: 'string',
    description: 'URL used in learning mode.',
  },
  {
    key: 'NAV_BAR_ACTIONS',
    scope: 'site',
    value: [],
    secret: false,
    valueType: 'array',
    description: 'Custom action buttons shown in the navigation bar.',
  },
  {
    key: 'GENAI_SDV_APP_ENDPOINT',
    scope: 'site',
    value: 'https://workflow.digital.auto/webhook/c0ba14bc-c6a3-4319-ad0a-ad89b1460b36',
    secret: false,
    valueType: 'string',
    description: 'GenAI endpoint URL for SDV App generation.',
    category: 'genai',
  },
  {
    key: 'SHOW_SDV_PROTOPILOT_BUTTON',
    scope: 'site',
    value: true,
    secret: false,
    valueType: 'boolean',
    description: "Show or hide the 'SDV ProtoPilot' GenAI button on the Prototype Code tab.",
    category: 'genai',
  },
  {
    key: 'USER_ASSET_TYPES',
    scope: 'site',
    value: ['CLOUD_RUNTIME', 'HARDWARE_KIT', 'GENAI-PYTHON'],
    secret: false,
    valueType: 'array',
    description: 'Asset types users can create and manage on the My Assets page.',
    category: 'general',
  },
  {
    key: 'GENAI_MARKETPLACE_URL',
    scope: 'site',
    value: 'https://store-be.digitalauto.tech',
    secret: false,
    valueType: 'string',
    description: 'Marketplace URL for fetching GenAI addons/generators.',
    category: 'genai',
  },
  {
    key: 'PROTOTYPE_ITEM_MENU_CONTEXT',
    scope: 'site',
    value: false,
    secret: false,
    valueType: 'boolean',
    description: 'Enable or disable the context menu on prototype items.',
    category: 'model_prototype',
  },
  {
    key: 'ALLOW_NON_ADMIN_ADDON_CONFIG',
    scope: 'site',
    value: true,
    secret: false,
    valueType: 'boolean',
    description: 'Allow non-admin model owners to add/manage addon tabs.',
    category: 'model_prototype',
  },
  {
    key: 'GRADIENT_HEADER',
    scope: 'site',
    value: false,
    secret: false,
    valueType: 'boolean',
    description: 'Apply a primary-to-secondary gradient to the main header.',
  },
  {
    key: 'PUBLIC_VIEWING',
    scope: 'site',
    value: true,
    secret: false,
    valueType: 'boolean',
    description: 'Allow unauthenticated users to view public content.',
  },
];

module.exports = PREDEFINED_SITE_CONFIGS;
