name: Notify Staging Update

on:
  workflow_run:
    workflows: ["Build and Push Images"]
    types:
      - completed
    branches:
      - v3-base

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deployment notification
        run: |
          echo "=========================================="
          echo "✓ Images pushed to GitHub Container Registry"
          echo "=========================================="
          echo ""
          echo "Images:"
          echo "  - ghcr.io/${{ github.repository }}/frontend:v3-base"
          echo "  - ghcr.io/${{ github.repository }}/frontend:v3-base-${{ github.sha }}"
          echo "  - ghcr.io/${{ github.repository }}/backend:v3-base"
          echo "  - ghcr.io/${{ github.repository }}/backend:v3-base-${{ github.sha }}"
          echo ""
          echo "Deployment:"
          echo "  Staging server will automatically deploy within 5 minutes"
          echo "  Using server-side polling (no webhook required)"
          echo ""
          echo "Monitoring:"
          echo "  ssh deploy@staging 'tail -f /var/log/autowrx-deploy.log'"
          echo "  ssh deploy@staging 'sudo journalctl -u autowrx-update.service -f'"
          echo ""
          echo "Manual trigger:"
          echo "  ssh deploy@staging '/opt/deploy/scripts/auto-update.sh'"
          echo ""
